apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: test-namespace
spec:
  destination:
    namespace: guestbook
    server: http://cluster-demo:8001
  sources:
    - path: guestbook
      repoURL: https://github.com/argoproj/argocd-example-apps
      targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
